const translations = {
	name: "Naam",
	email: "E-mail",
	customer: "Klant",
	a_customer: "Een klant",
	customers: "Klanten",
	employee: "Medewerker",
	an_employee: "Een medewerker",
	employees: "Medewerkers",
	task: "Taak",
	a_task: "Een taak",
	tasks: "Taken",
	appointment: "Afspraak",
	appointments: "Afspraken",
	an_appointment: "Een afspraak",
	add_task: "Taak Toevoegen",
	add_employee: "Medewerker Toevoegen",
	add_customer: "Klant Toevoegen",
	add_appointment: "Afspraak Toevoegen",
	userName: "Gebruikersnaam",
	password: "Wachtwoord",
	login_button : "Inloggen",
	forgot_password: "Vergeten",
	search: "Zoek",
	no_results: "Geen Resultaten",
	id: "ID",
	firstName: "Voornaam",
	lastName: "Achternaam",
	address: "Adres",
	postalCode: "Postcode",
	residence: "Woonplaats",
	role: "Rol",
	monday: "Maandag",
	tuesday: "Dinsdag",
	wednesday: "Woensdag",
	thursday: "Donderdag",
	friday: "Vrijdag",
	saturday: "Zaterdag",
	sunday: "Zondag",
	save: "Opslaan",
	signed_in: "Aangemeld",
	signed_out: "Afgemeld",
	customer_tasks: "Klant taken",
	standard_tasks: "Standaard taken",
	additionalInfo: "Additionele Informatie",
	time: "Tijd",
	expected_time: "Verwachte Tijd",
	confirmation: "Bevestiging",
	close: "Sluiten",
	duration: "Tijdsduur (min.)",
	activate: "Activeer",
	deactivate: "Deactiveer",
	starttime_and_endtime: "Begin- en Eindtijd",
	workSchedule: "Werkschema",
}

export default translations;