const translations = {
	name: "Naam",
	email: "E-mail",
	customer: "Klant",
	a_customer: "Een klant",
	customers: "Klanten",
	employee: "Medewerker",
	an_employee: "Een medewerker",
	employees: "Medewerkers",
	task: "Taak",
	a_task: "Een taak",
	tasks: "Taken",
	add_task: "Taak Toevoegen",
	add_employee: "Medewerker Toevoegen",
	add_customer: "Klant Toevoegen",
	userName: "Gebruikersnaam",
	password: "Wachtwoord",
	login_button : "Inloggen",
	forgot_password: "Vergeten",
	search: "Zoek",
	no_results: "Geen Resultaten",
	id: "ID",
	firstName: "Voornaam",
	lastName: "Achternaam",
	address: "Adres",
	postalCode: "Postcode",
	residence: "Woonplaats",
	role: "Rol",
	monday: "Maandag",
	tuesday: "Dinsdag",
	wednesday: "Woensdag",
	thursday: "Donderdag",
	friday: "Vrijdag",
	saturday: "Zaterdag",
	sunday: "Zondag",
	save: "Opslaan",

}

export default translations;